# Generated by Django 2.1.5 on 2019-01-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cantones',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=70)),
                ('latitud', models.DecimalField(decimal_places=16, max_digits=16)),
                ('longitud', models.DecimalField(decimal_places=16, max_digits=16)),
                ('descripcion', models.CharField(max_length=300)),
                ('imagen', models.ImageField(upload_to='cantones', verbose_name='Imagen')),
            ],
        ),
    ]
