# Generated by Django 2.1.5 on 2019-01-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cantones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantones',
            name='latitud',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
        migrations.AlterField(
            model_name='cantones',
            name='longitud',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
    ]
